### PR TITLE
Added login/logout visibility switch and a quote delete test

### PR DESCRIPTION
**Pull request by joncho26**
Anna,

Please review the following as I was unable to bundle install this app on my laptop ( ruby version clash)
1. Login/Logout on the top navigation bar should be visible based on the login status of the user
2. Added a quote delete test which should run fine as we tested that manually on Friday

### CODE REVIEW

**Comment by garygz** [comment]
Anna,

I actually created the last pull request. I had Jonathan logged in to my git for accidentally.

Gary

**Comment by I-love-ruby** [comment]
Jonathan Welcome to the party!

**Comment by aftaberski** [comment]
Hi Gary

Not sure what you mean by quote delete test but everything looks great!
I'll merge it now

Anna

**Comment by aftaberski** [comment]
I see what you mean about the quote delete test now. For some reason, the
last response is not returning ok, but the test checking to see if the
quote is deleted is returning fine...so I'm going to delete the
"expect(last_response).to be_ok" part.

I'll create a pull request to merge to master now if you want to just give
it another look quickly before merging

Thanks!

**Pull request merged**
